function [ objPlot ] = PlotObject( vertices, color, style, width )
%PLOTOBJECT Summary of this function goes here
%   Detailed explanation goes here

hold on

objPlot = plot( vertices(:,1), vertices(:,2), ...
      'Color', color, ...
      'LineStyle', style, ...
      'LineWidth', width, ...
      'Marker', 'o',...
      'MarkerSize', 10, ...
      'MarkerFaceColor', color, ...
      'MarkerEdgeColor', color);

hold off
